<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Chartis.Pdf.Infrastructure\Chartis.Pdf.Infrastructure.csproj" />
    <ProjectReference Include="..\Chartis.Pdf.Application\Chartis.Pdf.Application.csproj" />
    <ProjectReference Include="..\Chartis.Pdf.Domain\Chartis.Pdf.Domain.csproj" />
  </ItemGroup>
</Project>